Tracertly/urls.py
from django.contrib import admin
from django.contrib.auth import views as viewz
from django.urls import path, include, re_path
# from .routers import router
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),
    # path('accounts/login/', viewz.login, name='login'),
    path('accounts/login/', viewz.LoginView.as_view(), name="login"),
    path('accounts/logout/', viewz.LogoutView.as_view(), name='logout', kwargs={'next_page': '/'}),
    # path('api/', include(router.urls)),
    path('', views.home, name='home'),
    path('users/', include('users.urls')),
    path('boards/', include('boards.urls')),
    path('divisions/', include('divisions.urls')),
]

boards/urls.py
from django.urls import path, re_path
from boards.views import *

app_name = 'boards'
urlpatterns = [
    path('all/', BoardList.as_view(), name='board-list'),
    path('my-boards/user-<int:user_id>/all', UserBoards.as_view(), name='user-boards'),
    path('board/<int:board_id>/detail', BoardDetail.as_view(), name='board-detail'),
    path('board/add/', BoardCreate.as_view(), name='board-add'),
    path('board/<int:board_id>/update/', BoardUpdate.as_view(), name='board-update'),
    path('board/<int:board_id>/delete/', BoardDelete.as_view(), name='board-delete'),
    path('board/<int:board_id>/listing/<int:listing_id>/detail', ListingDetail.as_view(), name='listing-detail'),
    path('board/<int:board_id>/listing/add/', ListingCreate.as_view(), name='listing-add'),
    path('board/<int:board_id>/listing/<int:listing_id>/update/', ListingUpdate.as_view(), name='listing-update'),
    path('board/<int:board_id>/listing/<int:listing_id>/delete/', ListingDelete.as_view(), name='listing-delete'),
    path('board/<int:board_id>/listing/<int:listing_id>/item/add', ItemCreate.as_view(), name='item-add'),
    path('board/<int:board_id>/listing/<int:listing_id>/item/<int:item_id>/detail', ItemDetail.as_view(), name='item-detail'),
    path('board/<int:board_id>/listing/<int:listing_id>/item/<int:item_id>/update', ItemUpdate.as_view(), name='item-update'),
    path('board/listing/item/<int:item_id>/milestone/add', MilestoneCreate.as_view(), name='milestone-add'),
    path('board/listing/item/<int:item_id>/milestone/<int:milestone_id>/update', MilestoneUpdate.as_view(), name='milestone-update'),
    path('board/listing/item/<int:item_id>/milestone/<int:milestone_id>/update', milestoneAjaxUpdate, name='milestone-ajax-update'),
    path('board/listing/item/<int:item_id>/comment/add', CommentCreate.as_view(), name='comment-add'),
]

users/urls.py
from django.urls import path, re_path
from . import views
from .views import UserProfileCreate, UserProfileDetail, UserProfileUpdate

app_name = 'users'
urlpatterns = [
    path('new-user/', views.signup, name='create-user'),
    path('create-profile/', UserProfileCreate.as_view(), name='create-profile'),
    path('user/<int:user_id>/profile-detail/<int:profile_id>', UserProfileDetail.as_view(), name='profile-detail'),
    path('user/<int:user_id>/profile/<int:profile_id>/update', UserProfileUpdate.as_view(), name='update-profile'),
]

boards/models.py
from django.db import models
from divisions.models import *
from django.utils import timezone
from django.urls import reverse
from ckeditor.fields import RichTextField

class Base(models.Model):
	"""
		A Base Model (Mixin Like) for the creation of Section and Team Models through Inheritance
	"""
	name = models.CharField(max_length = 50)
	description = models.TextField(blank = True)
	creator = models.ForeignKey('auth.User', on_delete = models.PROTECT)
	created = models.DateTimeField(default = timezone.now)

	class Meta:
		abstract = True

	def __str__(self):
		return self.name

class Board(Base):
	"""
		A Board can be used either as a Messaging Panel, Project or similar 
	"""
	section = models.ForeignKey('divisions.Section', related_name='board_sections', on_delete = models.PROTECT)
	public = models.BooleanField(default=False) # Determine if the board if for public viewing
	archived = models.BooleanField(default=False) # Determine if the board's term has expired

	def get_absolute_url(self):
		return reverse('boards:board-detail', kwargs={'board_id': self.pk})

class Listing(Base):
	"""
		A Listing can be seen as a list of topics under the Board
	"""
	board = models.ForeignKey(Board, related_name ="listing_boards", on_delete = models.PROTECT)

	def get_absolute_url(self):
		# return reverse('boards:listing-detail', kwargs={'board_id': self.board.pk, 'listing_id': self.pk})
		return reverse('boards:board-detail', kwargs={'board_id': self.board.pk})

class Item(Base):
	"""
		An Item can be seen as Tasks under each Listing
	"""
	description = RichTextField()
	Listing = models.ForeignKey(Listing, related_name ="item_listings", on_delete = models.PROTECT)
	assignee = models.ForeignKey('auth.User', on_delete = models.PROTECT, related_name="item_assignee", blank=True, null=True)
		
	def get_absolute_url(self):
		return reverse('boards:board-detail', kwargs={'board_id': self.Listing.board.pk})

class Comment(models.Model):
	"""
		Users (Members) can get to comment on Items: A conversation
	"""
	item = models.ForeignKey(Item, on_delete=models.CASCADE, related_name='item_comments')
	comment = RichTextField()
	comment_date = models.DateTimeField(default=timezone.now)
	comment_by = models.ForeignKey('auth.User', on_delete = models.PROTECT)
	
	class Meta:
		ordering = ('-comment_date',)

	def __str__(self):
		return self.comment
	
	def get_absolute_url(self):
		return reverse('boards:item-detail', kwargs={'board_id': self.item.Listing.board.pk, 'listing_id': self.item.Listing.pk, 'item_id': self.item.pk})

class Milestone(models.Model):
	title = models.CharField(max_length=30, default='MileStone Title')
	status = models.BooleanField(default=False)
	item = models.ForeignKey(Item, on_delete=models.PROTECT)
	creator = models.ForeignKey('auth.User', on_delete = models.PROTECT)

	def __str__(self):
		return self.title
	
	def get_absolute_url(self):
		return reverse('boards:item-detail', kwargs={'board_id': self.item.Listing.board.pk, 'listing_id': self.item.Listing.pk, 'item_id': self.item.pk})

boards/forms.py
from django import forms
from boards.models import *
# from tinymce.widgets import TinyMCE
from ckeditor.widgets import CKEditorWidget

class BoardForm(forms.ModelForm):
    description = forms.CharField(widget=CKEditorWidget())
    class Meta:
        model = Board
        # fields = '__all__'
        fields = ['name', 'description']
        # widgets = { 'description': CKEditorWidget()}

boards/views/views_boards.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from boards.models import *
from boards.forms import BoardForm
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin

class BoardList(ListView):
	model = Board
	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['header'] = "All Boards"
		context['sub_header'] = "A list of all Boards Ever Created in this System"
		return context

class UserBoards(ListView):
	model = Board
	template_name = 'boards/user-boards.html'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		# get the request / logged on user
		user = self.request.user
		# Get all the boards the user has created
		user_boards = Board.objects.filter(creator=user)
		context['header'] = "My Boards"
		context['sub_header'] = "These are the boards you created."
		context['user_boards'] = user_boards
		return context

class BoardDetail(DetailView):
	model = Board
	context_object_name = 'board_detail'
	pk_url_kwarg = 'board_id'
	
	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		board_listings = Listing.objects.all().filter(board=self.get_object()) # name=self.object.name
		all_items = Item.objects.all()
		context['board_listings'] = board_listings
		context['all_items'] = all_items
		return context
	
class BoardCreate(LoginRequiredMixin, CreateView):
	model = Board
	fields = ['name', 'description','section', 'public', 'archived']
	template_name = 'create-form.html'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['formTitle'] = "Create Board"
		return context

	def form_valid(self, form):
		form.instance.creator = self.request.user
		return super().form_valid(form)

class BoardUpdate(UpdateView):
	model = Board
	pk_url_kwarg = 'board_id'
	fields = ['name', 'description','section', 'public', 'archived']
	template_name = 'create-form.html'

class BoardDelete(DeleteView):
	model = Board
	pk_url_kwarg = 'board_id'
	template_name = 'confirm-delete.html'
	success_url = "/"

boards/views/views_comment.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from boards.models import *
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from boards.mixins import AjaxableResponseMixin
from django.http import JsonResponse


class CommentCreate(LoginRequiredMixin, AjaxableResponseMixin, CreateView):
    model = Comment
    fields = ['comment']
    pk_url_kwarg = 'comment_id'

    # def form_valid(self, form):
    #     form.instance.comment_by = self.request.user
    #     item = get_object_or_404(Item, pk=self.kwargs.get('item_id'))
    #     form.instance.item = item
    #     return super().form_valid(form)
   
    def form_valid(self, form):
        form.instance.comment_by = self.request.user
        item = get_object_or_404(Item, pk=self.kwargs.get('item_id'))
        form.instance.item = item

        response = super().form_valid(form)
        if self.request.is_ajax():
            data = {
                'message': "Successfully submitted form data."
            }
            return JsonResponse(data)
        else:
            return response

class CommentUpdate(UpdateView):
	model = Comment
	# form_class = ListingForm
	fields = ['comment']
	pk_url_kwarg = 'comment_id'

class CommentDelete(DeleteView):
	model = Comment
	pk_url_kwarg = 'comment_id'
	success_url = "/"

boards/views/views_items.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from boards.models import *
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin

class ItemDetail(DetailView):
	model = Item
	context_object_name = 'item_detail'
	pk_url_kwarg = 'item_id'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		item = get_object_or_404(Item, pk=self.kwargs.get('item_id'))
		assignee = None
		assigned = None
		full_name = None
		if item.assignee:
			if item.assignee.first_name and item.assignee.last_name:
				firstname = item.assignee.first_name[:1]
				lastname = item.assignee.last_name[:1]
				full_name = item.assignee.first_name.capitalize() + " " + item.assignee.last_name.capitalize()
				initials = firstname + lastname
				assignee = initials.upper()
				assigned = "initialz"
			else:
				assignee = "@" + str(item.assignee)
				assigned = "usernem"
		comments = item.item_comments.all()
		milestones = item.milestone_set.all()
		context['header'] = "All Boards"
		context['assignee'] = assignee
		context['full_name'] = full_name
		context['assigned'] = assigned
		context['milestones'] = milestones
		context['comments'] = comments
		commentCreateURL = "board/listing/item/" + str(item.pk) + "/comment/add"
		context['commentCreateURL'] = commentCreateURL
		return context

class ItemCreate(LoginRequiredMixin, CreateView):
	model = Item
	fields = ['name', 'description']
	pk_url_kwarg = 'item_id'
	template_name = 'create-form.html'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['formTitle'] = "Add Item"
		return context

	def form_valid(self, form):
		form.instance.creator = self.request.user
		listing = get_object_or_404(Listing, pk=self.kwargs.get('listing_id'))
		form.instance.Listing = listing
		return super().form_valid(form)

class ItemUpdate(UpdateView):
	model = Item
	fields = ['name', 'description', 'assignee']
	pk_url_kwarg = 'item_id'
	template_name = 'create-form.html'

class ItemDelete(DeleteView):
	model = Item
	pk_url_kwarg = 'item_id'
	success_url = "/"

boards/views/views_listings.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from boards.models import *
# from boards.forms import ListingForm
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin

class ListingDetail(DetailView):
	model = Listing
	context_object_name = 'listing_detail'
	pk_url_kwarg = 'listing_id'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		return context
	
class ListingCreate(LoginRequiredMixin, CreateView):
	model = Listing
	fields = ['name', 'description']
	pk_url_kwarg = 'listing_id'
	template_name = 'create-form.html'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['formTitle'] = "Add Listing"
		return context

	def get_initial(self):
		board = get_object_or_404(Board, pk=self.kwargs.get('board_id'))
		return {'board':board.pk}

	def form_valid(self, form):
		form.instance.creator = self.request.user
		board = get_object_or_404(Board, pk=self.kwargs.get('board_id'))
		form.instance.board = board
		return super().form_valid(form)

class ListingUpdate(UpdateView):
	model = Listing
	# form_class = ListingForm
	fields = ['name', 'description']
	pk_url_kwarg = 'listing_id'
	template_name = 'create-form.html'

class ListingDelete(DeleteView):
	model = Listing
	pk_url_kwarg = 'listing_id'
	template_name = 'confirm-delete.html'
	success_url = "/"

boards/views/views_milestone.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from boards.models import *
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from boards.mixins import AjaxableResponseMixin
from django.http import JsonResponse


class MilestoneCreate(LoginRequiredMixin, CreateView):
	model = Milestone
	fields = ['title', 'status']
	pk_url_kwarg = 'milestone_id'

	def form_valid(self, form):
		form.instance.creator = self.request.user
		item = get_object_or_404(Item, pk=self.kwargs.get('item_id'))
		form.instance.item = item
		return super().form_valid(form)

class MilestoneUpdate(UpdateView):
	model = Milestone
	fields = ['title', 'status']
	pk_url_kwarg = 'milestone_id'

def milestoneAjaxUpdate(request, milestone_id):
	if request.method == "POST" and request.is_ajax():
		status = request.POST['status']
		milestone = get_object_or_404(Milestone, pk=milestone_id)
		milestone.status = status
		milestone.save()
		data = {
			'message': "Successfully update milestone"
		}
		return JsonResponse(data)
	else:
		return JsonResponse({'status':'Failed'})

class MilestoneDelete(DeleteView):
	model = Milestone
	pk_url_kwarg = 'milestone_id'
	success_url = "/"

boards/templates/boards/board_list.html
{% extends 'base.html' %}

{% block content %}
	<div class="row">
		<div class="col-8">
			<h3>
				{{ header }} 
			</h3>
		</div>
		<div class="col-3"> 
			<a class="float-right add-color" href="{% url 'boards:board-add' %}">
				Create Board	
			</a>
		</div>
	</div>
	<hr>
	<p class="lead text-muted bg-white">{{ sub_header }}</p>
	<hr>
	<div class="card-columns">
		{% for board in object_list %}	
			<!-- Board -->	
			<div class="card">
				<div class="card-body board-color">
				    <h5 class="card-title"> 
				    	<a href="{% url 'boards:board-detail' board_id=board.pk %}" class="card-link text-center">{{ board.name }}</a>
				    </h5>
				    <hr>
					  <div class="card-body">
					    <p class="card-text bg-white">
					    	{{ board.description }}
					    	<span class="cardTextMore">
					    		<a href="#">
					    			<i class="far fa-edit"></i>
					    		</a>
					    	</span>
					    </p>
					</div>
					<hr>		   
				</div>
			</div>
			<!-- / Board -->
		{% endfor %}

		<div class="card-body">
			<p class="card-text pl-1 add-color">
				<a href="{% url 'boards:board-add' %}">Create Board</a>
			</p>
		</div>


	</div>
	
{% endblock %}

boards/templates/boards/item_detail.html
{% extends 'base.html' %}

{% block content %}

	<div class="">
		<div class="item-content" >
			<div class="item-header">
				<h5 class="item-title" id="">
				Task:	{{ item_detail.name }}
				</h5>
			</div>
			<div class="item-body card" style="padding-top: 2rem !important;">
				<div class="row">
					<div class="col-10">
						<div class="row" >
							<div class="col-1">
								<i class="fas fa-align-right faSize-bg"></i>
							</div>
							<div class="col-11">
								<h6>Description: <a href="{% url 'boards:item-update' board_id=item_detail.Listing.board.pk listing_id=item_detail.Listing.pk  item_id=item_detail.pk %}"><i class="fas fa-pencil-alt faSize-bg"></i></a></h6>
								<hr>
								<div class="card-subtitle">
									{{ item_detail.description|safe }}
								</div>
								<hr>
							</div>
							<div class="col-1">
								<i class="fas fa-tasks  faSize-bg"></i>
							</div>
							<div class="col-11">
								<h6>MILESTONES: <span class="revealMilestone"><i class="fas fa-plus faSize-bg"></i></span></h6>
								<hr>
								<div class="addMilestone" style="display:none">
									<form id="addMilestoneForm" method='POST' action='{% url 'boards:milestone-add' item_id=item_detail.pk %}' >
										{% csrf_token %}
										<div class="row">
											<div class="col-6">
												<input id="milestone" class="form-control form-control-sm" type="text" placeholder="Add Milestone ...">	      							
											</div>
											<div class="col-2">
												<button type="submit"  class="btn btn-info">Add</button>
											</div>
										</div>		      						
									</form>
									<hr>
								</div>
								{% for measure in milestones %}
									<div class="form-check form-check-inline">
										{% if measure.status == True %}		
										<input update-url="{% url 'boards:milestone-ajax-update' item_id=item_detail.pk milestone_id=measure.pk %}" class="form-check-input milestone" type="checkbox" id="{{ measure.title }}" title="{{ measure.title }}" value="{{ measure.status }}" hidden>
										<span class="text-success"><i class="fa fa-check-circle" aria-hidden="true"></i></span>				
										{% else %}
										<input update-url="{% url 'boards:milestone-ajax-update' item_id=item_detail.pk milestone_id=measure.pk %}" class="form-check-input milestone" type="checkbox" id="{{ measure.title }}" title="{{ measure.title }}" value="{{ measure.status }}" hidden>
											<span class="text-danger"><i class="fa fa-minus" aria-hidden="true"></i></span><!-- minus-circle times times-circle -->
										{% endif %}
										<label class="form-check-label" for="{{ measure.title }}" style="margin-left:0.25rem;">{{ measure.title }}</label>
									</div>
									<!-- <i class="fas fa-check-circle"></i> <i class="fas fa-times-circle"></i> -->
								{% endfor %}
								<hr>
							</div>
							<div class="col-1">
								<i class="far fa-comment faSize-bg"></i>
							</div>
							<div class="col-11">
								<h5>Write Comment: 
									<!-- <a href="{% url 'boards:comment-add' item_id=item_detail.pk %}" type="submit" style="margin-top: 60%; padding:1rem;">Add a Commet</a> -->
								</h5>
								<hr>
								<form id="itemCommentForm" method='POST' action='{% url 'boards:comment-add' item_id=item_detail.pk %}' data-url='{{ commentCreateURL }}'>
									{% csrf_token %}
									{{ form.media }}
									<div class="row">
										<label for="comment" hidden>Comment</label>
										<div class="col-10">
											<textarea class="form-control" id="comment" rows="3"></textarea>		      							
										</div>
										<div class="col-2">
											<button type="submit" style="margin-top: 60%" class="btn btn-info">Commit</button>
										</div>
									</div>		      						
								</form>
								<hr>
								<h6>Comments</h6>
								<hr>
								<div class="row">
									{% for comment in comments %}
										<div class="col-2 commentor" style="margin-bottom: 1rem;">
											<h6>{{ comment.comment_by }}</h6>
											<p class="lead" style="font-size:0.5rem;"><small>{{ comment.comment_date }}</small></p>
										</div>
										<div class="col-10 comment" style="margin-bottom: 1rem;">
												{{ comment.comment }}

										<hr>
										</div>
									{% endfor %}
								</div>
							</div>
						</div>
					</div>
					<div class="col-2">
						<hr>
						<div class="btn-group-vertical btn-group-sm">
							{% if not assignee %}
								<a href="{% url 'boards:item-update'  board_id=item_detail.Listing.board.pk listing_id=item_detail.Listing.pk  item_id=item_detail.pk  %}" class="btn btn-info"><i class="fas fa-user"></i> Assignee</a>
							{% else %}
								<div class="d-flex justify-content-around align-items-center">
									<span class="mr-2">
										<a href="{% url 'boards:item-update'  board_id=item_detail.Listing.board.pk listing_id=item_detail.Listing.pk  item_id=item_detail.pk  %}"><i class="fas fa-user"></i></a>
									</span>
									{% if full_name %}
										<span class="assignee {{ assigned }}" data-toggle="tooltip" data-placement="bottom" title="{{ full_name }}">{{ assignee }}</span>
									{% else %}
										<span class="assignee {{ assigned }}">{{ assignee }}</span>
									{% endif %}
								</div>
							{% endif %}
						</div>
						<hr>
					</div>
				</div>
			</div>
			<div class="item-footer">
			</div>
		</div>
	</div>

{% endblock %}



{% block scripts %} 

<script>

	$(document).ready(function(){

		// CommentForm Submit with Ajax
		var $myForm = $('#itemCommentForm')
        $myForm.submit(function(event){
            event.preventDefault();
			//var $formData = $(this).serialize();
			var $formData = {
				comment: $("#comment").val(),
			}
            var $thisURL = $myForm.attr('action');
            $.ajax({
                method: "POST",
                url: $thisURL,
                data: $formData,
                success: handleFormSuccess,
                error: handleFormError,
            });
        });

        function handleFormSuccess(data, textStatus, jqXHR){
			$myForm[0].reset(); // reset form data
			window.location.reload();
        }

        function handleFormError(jqXHR, textStatus, errorThrown){
            console.log(jqXHR)
            console.log(textStatus)
            console.log(errorThrown)
		}
		
		// Milestone status update
		$("input.milestone").on('click', function(e){
			var inputStatus = $(this).val();
			var updateURL = $(this).attr('update-url');
			if(inputStatus === 'True'){
				// Change to False
				inputStatus = {
					'csrfmiddlewaretoken': "{{ csrf_token }}",
					title : $(this).attr("title"),
					status: 'False',
				}
			}
			if(inputStatus === 'False'){
				// Change to True
				inputStatus = {
					'csrfmiddlewaretoken': "{{ csrf_token }}",
					title : $(this).attr("title"),
					status: 'True',
				}
			}
			//axios.defaults.xsrfCookieName = 'csrftoken';
			//axios.defaults.xsrfHeaderName = 'X-CSRFToken';
			//axios.put(updateURL, inputStatus)
			//	.then(function(data){
			//		console.log(data)
			//	});
			$.ajax({
                method: "POST",
                url: updateURL,
				data: inputStatus,
                success: function(){
					window.location.reload();
				},
                error: function(){},
            });
		});

		// Reveal Add Milestone Form
		$('.revealMilestone').on('click', function(e){
			$('.addMilestone').removeAttr("style");
		});

		// Submit Add Milestone Form
		$("form#addMilestoneForm").on('submit', function(e){
			e.preventDefault();
			var milestone = $("input#milestone").val();
			var url = $(this).attr('action');
			data = {
				title : milestone,
				status: 'False',
			}
			console.log(data);
			console.log(url);
			console.log(milestone);
			$.ajax({
                method: "POST",
                url: url,
				data: data,
                success: function(){
					window.location.reload();
					$('form#addMilestoneForm')[0].reset();
				},
                error: function(){},
            });
		});

	});



</script>



{% endblock %}

boards/templates/boards/milestone_form.html
{% extends 'base.html' %}

{% block content %}
    <h3>Create Board Here exe</h3>
    <hr>
    <p class="lead">It works !!!</p>

    <br>
    <form method="POST" class="form-horizontal post-form" id="editBase">{% csrf_token %}
        <p class="availableMessage" hidden="hidden"></p>
        {% for field in form %}
            <div class="form-group fieldWrapper">
                {{ field.errors }}
                <div class="col-sm-2">
                  {% if field.is_hidden %}
                    {# Hide Label #}
                  {% else %}
                    {{ field.label_tag }}
                  {% endif %}
                </div>
                <div class="col-sm-10">
                    {{ field }}
                </div>
                {% if field.help_text %}
                    <p class="help">{{ field.help_text|safe }}</p>
                {% endif %}
            </div>
        {% endfor %}
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-primary">Save</button>
            </div>
        </div>
    </form>





{% endblock %}

boards/templates/boards/user-boards.html
{% extends 'base.html' %}

{% block content %}
	<div class="row">
		<div class="col-8">
			<h3>
				{{ header }} 
			</h3>
		</div>
		<div class="col-3"> 
			<a class="float-right add-color" href="{% url 'boards:board-add' %}">
				Create Board	
			</a>
		</div>
    </div>
    <hr>
	<p class="lead text-muted bg-white">{{ sub_header }}</p>
    <hr>
	<div class="card-columns">
        {% if user_boards|length == 0 %}
            <p class="lead">
                You have no created any boards yet. Need Help? Start <a href="{% url 'boards:board-add' %}">here</a>
            </p>
        {% else %}
            {% for board in user_boards %}	
                <!-- Board -->	
                <div class="card">
                    <div class="card-body board-color">
                        <h5 class="card-title"> 
                            <a href="{% url 'boards:board-detail' board_id=board.pk %}" class="card-link text-center">{{ board.name }}</a>
                        </h5>
                        <hr>
                        <div class="card-body bg-white">
                            <p class="card-text">
                                {{ board.description }}
                                <span class="cardTextMore">
                                    <a href="#">
                                        <i class="far fa-edit"></i>
                                    </a>
                                </span>
                            </p>
                        </div>
                        <hr>		   
                    </div>
                </div>
                <!-- / Board -->
            {% endfor %}

            <div class="card-body">
                <p class="card-text pl-1 add-color">
                    <a href="{% url 'boards:board-add' %}">Create Board</a>
                </p>
            </div>
        {% endif %}


	</div>
	
{% endblock %}