Tracertly/urls.py
from django.contrib import admin
from django.contrib.auth import views as viewz
from django.urls import path, include, re_path
# from .routers import router
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),
    # path('accounts/login/', viewz.login, name='login'),
    path('accounts/login/', viewz.LoginView.as_view(), name="login"),
    path('accounts/logout/', viewz.LogoutView.as_view(), name='logout', kwargs={'next_page': '/'}),
    # path('api/', include(router.urls)),
    path('', views.home, name='home'),
    path('users/', include('users.urls')),
    path('boards/', include('boards.urls')),
    path('divisions/', include('divisions.urls')),
]

users/urls.py
from django.urls import path, re_path
from . import views
from .views import UserProfileCreate, UserProfileDetail, UserProfileUpdate

app_name = 'users'
urlpatterns = [
    path('new-user/', views.signup, name='create-user'),
    path('create-profile/', UserProfileCreate.as_view(), name='create-profile'),
    path('user/<int:user_id>/profile-detail/<int:profile_id>', UserProfileDetail.as_view(), name='profile-detail'),
    path('user/<int:user_id>/profile/<int:profile_id>/update', UserProfileUpdate.as_view(), name='update-profile'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
 
class UserProfile(models.Model):
    user = models.OneToOneField('auth.User', related_name='user_profile', on_delete=models.PROTECT)
    title = models.CharField(max_length=255, blank=True, default='e.g Accountant')
    phone = models.CharField(max_length=20, blank=True, default='')
    teams = models.ManyToManyField('divisions.Team', related_name='user_teams', blank = True)
    section = models.ForeignKey('divisions.Section', related_name='user_section', on_delete=models.PROTECT, blank = True, null = True)
    status = models.CharField(max_length=100, blank=True, null=True, default='Mood? :)')
    about = models.TextField(default='Who are you?', blank=True)

    def get_absolute_url(self):
        return reverse('users:profile-detail', kwargs={'user_id': self.user.pk, 'profile_id':self.pk})

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )
        
# class UserForm(forms.ModelForm):
#     class Meta:
#         model = User
#         fields = ['first_name', 'last_name', 'email']

users/views.py
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import DetailView
from django.views.generic.edit import CreateView, UpdateView
from .forms import SignUpForm
from .models import UserProfile
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from boards.mixins import AjaxableResponseMixin
from django.http import JsonResponse

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('home')
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form': form})


class UserProfileDetail(DetailView):
	model = UserProfile
	context_object_name = 'profile'
	pk_url_kwarg = 'profile_id'
	template_name = 'users/profile.html'
	
	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		return context
	
class UserProfileCreate(LoginRequiredMixin, CreateView):
	model = UserProfile
	fields = ['title', 'phone','teams', 'section', 'status', 'about']
	template_name = 'users/create-profile.html'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['formTitle'] = "Create your Profile"
		return context

	def form_valid(self, form):
		form.instance.user = self.request.user
		return super().form_valid(form)

class UserProfileUpdate(LoginRequiredMixin, UpdateView):
	model = UserProfile
	fields = ['title', 'phone','teams', 'section', 'status', 'about']
	template_name = 'create-form.html'
	pk_url_kwarg = 'profile_id'

users/templates/users/create-profile.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-10 offset-2 text-center">                
                <h2>My Profile</h2>
                <p class="lead">For the best results, please complete the following</p>
                <hr>
            </div>
            <div class="col-8 offset-4">
                <form method="post">
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="form-group row">
                        <label for="staticEmail" class="col-2 col-form-label">{{ field.label_tag }}</label>
                        <div class="col-10">
                            {{ field }}
                            {% for error in field.errors %}
                                <div class="alert alert-danger" role="alert">                            
                                    <p>{{ error }}</p>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                    {% endfor %}
                    <div class="form-group row">
                        <div class="col-10 offset-2">
                            <button type="submit" class="btn btn-primary">Save</button>
                        </div>
                    </div>
                </form>                
            </div>
        </div>
    </div>


{% endblock %}

users/templates/users/profile.html
{% extends 'base.html' %}

{% block content %}

 <div class="container">
     <br>
    <h3>Your Profile</h3>
    <hr>
     <div class="row bg-white space-around">
            <!-- profile info -->
         <div class="col-8">
            <div class="row">
                <div class="col-2 text-bold">
                    Full Name:
                </div>
                <div class="col-10">
                  {% if profile.user.first_name %}  
                    {{ profile.user.first_name }} {{ profile.user.last_name }} 
                  {% else %} 
                  <p class="text-warning">
                        No Name. To Update, Contact System Administrator
                  </p>                    
                   {% endif %}
                    <hr>
                </div>
                <div class="col-2 text-bold">
                    Contact 
                    <small class="text-muted text-tiny">(Cell/Phone)</small>
                </div>
                <div class="col-10">
                    {% if profile.phone %}                       
                     {{ profile.phone }}
                    {% else %} 
                    <p class="text-warning">
                          No Contact iformation. Update <a href="{% url 'users:update-profile' user_id=profile.user.pk profile_id=profile.pk %}">here</a>
                    </p>                    
                     {% endif %}
                    <hr>
                </div>
                <div class="col-2 text-bold">
                    Title
                </div>
                <div class="col-10">
                        {% if profile.title %}                       
                         {{ profile.title }}
                        {% else %} 
                        <p class="text-warning">
                              No Title, Who are you?. Update <a href="{% url 'users:update-profile' user_id=profile.user.pk profile_id=profile.pk %}">here</a>
                        </p>                    
                         {% endif %}
                    <hr>
                </div>
                <div class="col-2 text-bold">
                    My Teams
                </div>
                <div class="col-10">
                    {% for team in profile.teams.all %}
                        {{ team }},
                    {% empty %}
                        You do not belong to any team yet
                    {% endfor %}
                    <hr>
                </div>
                <div class="col-2 text-bold">
                    Section
                </div>
                <div class="col-10">
                    {{ profile.section }}
                    <hr>
                </div>
                <div class="col-2 text-bold">
                    Status
                </div>
                <div class="col-10">
                    {{ profile.status }}
                    <hr>
                </div>
                <div class="col-2 text-bold">
                    About Me
                </div>
                <div class="col-10">
                    {{ profile.about }}
                    <hr>
                </div>                    
            </div>
         </div> <!-- / profile info -->
         
        <!-- profile badges -->
         <div class="col-4">
            Badged and other info will be here
         </div> <!-- / profile badges -->
     </div>
 </div>

{% endblock %}