Tracertly/urls.py
from django.contrib import admin
from django.contrib.auth import views as viewz
from django.urls import path, include, re_path
# from .routers import router
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),
    # path('accounts/login/', viewz.login, name='login'),
    path('accounts/login/', viewz.LoginView.as_view(), name="login"),
    path('accounts/logout/', viewz.LogoutView.as_view(), name='logout', kwargs={'next_page': '/'}),
    # path('api/', include(router.urls)),
    path('', views.home, name='home'),
    path('users/', include('users.urls')),
    path('boards/', include('boards.urls')),
    path('divisions/', include('divisions.urls')),
]

boards/urls.py
from django.urls import path, re_path
from boards.views import *

app_name = 'boards'
urlpatterns = [
    path('all/', BoardList.as_view(), name='board-list'),
    path('my-boards/user-<int:user_id>/all', UserBoards.as_view(), name='user-boards'),
    path('board/<int:board_id>/detail', BoardDetail.as_view(), name='board-detail'),
    path('board/add/', BoardCreate.as_view(), name='board-add'),
    path('board/<int:board_id>/update/', BoardUpdate.as_view(), name='board-update'),
    path('board/<int:board_id>/delete/', BoardDelete.as_view(), name='board-delete'),
    path('board/<int:board_id>/listing/<int:listing_id>/detail', ListingDetail.as_view(), name='listing-detail'),
    path('board/<int:board_id>/listing/add/', ListingCreate.as_view(), name='listing-add'),
    path('board/<int:board_id>/listing/<int:listing_id>/update/', ListingUpdate.as_view(), name='listing-update'),
    path('board/<int:board_id>/listing/<int:listing_id>/delete/', ListingDelete.as_view(), name='listing-delete'),
    path('board/<int:board_id>/listing/<int:listing_id>/item/add', ItemCreate.as_view(), name='item-add'),
    path('board/<int:board_id>/listing/<int:listing_id>/item/<int:item_id>/detail', ItemDetail.as_view(), name='item-detail'),
    path('board/<int:board_id>/listing/<int:listing_id>/item/<int:item_id>/update', ItemUpdate.as_view(), name='item-update'),
    path('board/listing/item/<int:item_id>/milestone/add', MilestoneCreate.as_view(), name='milestone-add'),
    path('board/listing/item/<int:item_id>/milestone/<int:milestone_id>/update', MilestoneUpdate.as_view(), name='milestone-update'),
    path('board/listing/item/<int:item_id>/milestone/<int:milestone_id>/update', milestoneAjaxUpdate, name='milestone-ajax-update'),
    path('board/listing/item/<int:item_id>/comment/add', CommentCreate.as_view(), name='comment-add'),
]

divisions/urls.py
from django.urls import path, re_path
from divisions.views import (
    SectionList, SectionDetail, SectionCreate, SectionUpdate, SectionDelete,
    TeamList, TeamDetail, TeamCreate, TeamUpdate, TeamDelete
)

app_name = 'divisions'
urlpatterns = [
    path('sections/', SectionList.as_view(), name='section-list'),
    path('section-detail/<int:section_id>/', SectionDetail.as_view(), name='section-detail'),
    path('section/add/', SectionCreate.as_view(), name='section-add'),
    path('section/<int:section_id>/update', SectionUpdate.as_view(), name='section-update'),
    path('teams/', TeamList.as_view(), name='team-list'),
    path('team-detail/<int:team_id>/', TeamDetail.as_view(), name='team-detail'),
    path('team/add/', TeamCreate.as_view(), name='team-add'),
    path('team/<int:team_id>/update', TeamUpdate.as_view(), name='team-update'),
]

users/urls.py
from django.urls import path, re_path
from . import views
from .views import UserProfileCreate, UserProfileDetail, UserProfileUpdate

app_name = 'users'
urlpatterns = [
    path('new-user/', views.signup, name='create-user'),
    path('create-profile/', UserProfileCreate.as_view(), name='create-profile'),
    path('user/<int:user_id>/profile-detail/<int:profile_id>', UserProfileDetail.as_view(), name='profile-detail'),
    path('user/<int:user_id>/profile/<int:profile_id>/update', UserProfileUpdate.as_view(), name='update-profile'),
]

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Tracertly</title>
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/bootstrap.min.css' %}">    <!-- faontawesome js-->
    <script src="{% static 'fontawesome/js/fontawesome-all.js' %}"></script>
    <link rel="stylesheet" href="{% static 'fontawesome/css/fa-svg-with-js.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/tracertly.css' %}">
</head>
<body>
    <div id="main-wrapper">

        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
          <a class="navbar-brand" href="#" onclick="openNav()">Tracertly</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}">Home</a>
              </li>
            </ul>
           <ul class=" navbar-nav my-2 my-lg-0">
               {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            @{{ user.username }} 
                        </a>
                        <div class="dropdown-menu bg-dark" aria-labelledby="navbarDropdown">
                            {% if not user.user_profile %}
                                <a class="dropdown-item link-transition" href="{% url 'users:create-profile' %}">Create Profile</a>
                            {% else %}
                                <a class="dropdown-item link-transition" href="{% url 'users:profile-detail' user_id=user.pk profile_id=user.user_profile.pk %}">Profile</a>
                            {% endif %}
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item text-logout" href="{% url 'logout' %}">
                                Sign Out
                                <span class="fa fa-lock" aria-hidden="true"></span> 
                            </a>
                        </div>
                    </li>
                {% else %}
                    <li class="user-names nav-item"><a class="nav-link" href="{% url 'login' %}"><span class="fa fa-unlock-alt" aria-hidden="true"></span> Log In</a></li>
                {% endif %}
           </ul>
          </div>
        </nav>
        

        <div class="wrapper">
            <nav id="sideBarNav" class="sidenav">
                <ul class="list-group">
                    <a  href="#" class="list-group-item d-flex justify-content-center align-items-center ">
                        <b>DASHBOARD</b>
                    </a>
                    <a  href="{% url 'home' %}" class="list-group-item d-flex justify-content-between align-items-center link-transition">
                        Public Boards
                        <!-- <span class="badge badge-dark badge-pill">9</span></a> -->
                    </a>
                    {% if user.is_authenticated %}
                        <a  href="{% url 'boards:user-boards' user_id=user.pk %}" class="list-group-item d-flex justify-content-between align-items-center link-transition">
                        My Boards
                        <!-- <span class="badge badge-dark badge-pill">9</span></a> -->
                    </a>
                    {% endif %}
                    <a  href="{% url 'divisions:team-list' %}" class="list-group-item d-flex justify-content-between align-items-center link-transition">
                        Teams
                        <!-- <span class="badge badge-dark badge-pill">5</span> -->
                    </a>
                    <a  href="{% url 'divisions:section-list' %}" class="list-group-item d-flex justify-content-between align-items-center link-transition">
                        Sections
                        <!-- <span class="badge badge-dark badge-pill">5</span> -->
                    </a>
                    <a  href="#" class="list-group-item d-flex justify-content-between align-items-center link-transition">
                        Messages
                        <!-- <span class="badge badge-dark badge-pill">14</span> -->
                    </a>
                    <a  href="#" class="list-group-item d-flex justify-content-between align-items-center link-transition">
                        Howdy
                        <!-- see what others are doing  -->
                        <!-- <span class="badge badge-dark badge-pill">5</span> -->
                    </a>
                    <a  href="javascript:void(0)" class="list-group-item d-flex justify-content-center align-items-center closebtn" onclick="closeNav()">
                    <<- X </a>
                </ul>
            </nav>

            <main role="main" id="main" class="container-fluid">
                
                {% block content %}

                {% endblock %}

            </main>

        </div>
        
    </div>
    <footer class="tracertly-footer  text-center">
        Tracertly &copy 2018
    </footer>

    <!-- jQuery -->
    <script src="{% static 'jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'bootstrap/bootstrap.min.js' %}"></script>
    <!-- tracertly js -->
    <script src="{% static 'js/vue.min.js' %}"></script>
    <script src="{% static 'js/axios.min.js' %}"></script>
    <script src="{% static 'js/tracertly.js' %}"></script>
    {% block scripts %} {% endblock %}
</body>
</html>

templates/confirm-delete.html
{% extends 'base.html' %}

{% block content %}

    <div class="row">
        <div class="col-6 offset-3" style="margin-top:2rem;">
            <h4>Delete Confirmation</h4>
            <hr>
            <form method="post">
                {% csrf_token %}
                <div class="alert alert-warning" role="alert">
                    <p class="lead">You are about to delete: <b>{{ object }}</b></p>
                   <p> Are you sure? This is not reversible!</p>
                </div>
                <input type="submit" class="btn btn-danger" value="Delete"/>
            </form>
        </div>
    </div>    
    
{% endblock %}

templates/create-form.html
{% extends 'base.html' %}

{% block content %}

    <div class="row">
        <div class="col-6 offset-3 bg-white">
            <h3>{{ formTitle }}</h3>
            <hr>
        
            <br>
            <form method="POST" class="form-horizontal post-form" id="editBase">
                {% csrf_token %}
                {{ form.media }}
                <p class="availableMessage" hidden="hidden"></p>
                {% for field in form %}
                    <div class="form-group">
                        <div class="row">
                            {{ field.errors }}
                            <div class="col-2">
                                {% if field.is_hidden %}
                                {# Hide Label #}
                                {% else %}
                                {{ field.label_tag }}
                                {% endif %}
                            </div>
                            <div class="col-10">
                                {{ field }}
                            </div>
                            {% if field.help_text %}
                                <p class="help">{{ field.help_text|safe }}</p>
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
                <div class="form-group">
                    <div class="row">
                        <div class="col-10 offset-2 ">
                            <button type="submit" class="btn btn-primary">Save</button>
                        </div>
                    </div>
                </div>
            </form>
       </div>
    </div>
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block content %}
    
	<h3>{{ heading }}</h3>
	<hr>
	<p class="lead text-muted bg-white">{{ sub_header }}</p>
	<hr>
	{% if boards_count != 0 %}
	<div class="card-columns">
			{% for board in boards %}	
				<!-- Board -->	
				<div class="card">
					<div class="card-body board-color">
						<h5 class="card-title"> 
							<a href="{% url 'boards:board-detail' board_id=board.pk %}" class="card-link text-center">{{ board.name }}</a>
						</h5>
						<hr>
						<div class="card-body bg-white">
							<p class="card-text">
								{{ board.description }}
								<span class="cardTextMore">
									<a href="#">
										<i class="far fa-edit"></i>
									</a>
								</span>
							</p>
						</div>
						<hr>		   
					</div>
				</div>
				<!-- / Board -->
			{% endfor %}
		</div>
		{% else %}
			<!-- if boards do not exist on public notice board
			then tell the user that there are no public boards yet otherwise
			give then an ability to start creating some  -->
			<h3 class="spacer">Sorry! </h3>
			<p class="lead">There are no public boards yet. You might be the first one to create some.</p>
			<hr>

			<a href="{% url 'boards:board-add' %}">Create Board</a>
		{% endif %}

{% endblock %}