Tracertly/urls.py
from django.contrib import admin
from django.contrib.auth import views as viewz
from django.urls import path, include, re_path
# from .routers import router
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),
    # path('accounts/login/', viewz.login, name='login'),
    path('accounts/login/', viewz.LoginView.as_view(), name="login"),
    path('accounts/logout/', viewz.LogoutView.as_view(), name='logout', kwargs={'next_page': '/'}),
    # path('api/', include(router.urls)),
    path('', views.home, name='home'),
    path('users/', include('users.urls')),
    path('boards/', include('boards.urls')),
    path('divisions/', include('divisions.urls')),
]

boards/urls.py
from django.urls import path, re_path
from boards.views import *

app_name = 'boards'
urlpatterns = [
    path('all/', BoardList.as_view(), name='board-list'),
    path('my-boards/user-<int:user_id>/all', UserBoards.as_view(), name='user-boards'),
    path('board/<int:board_id>/detail', BoardDetail.as_view(), name='board-detail'),
    path('board/add/', BoardCreate.as_view(), name='board-add'),
    path('board/<int:board_id>/update/', BoardUpdate.as_view(), name='board-update'),
    path('board/<int:board_id>/delete/', BoardDelete.as_view(), name='board-delete'),
    path('board/<int:board_id>/listing/<int:listing_id>/detail', ListingDetail.as_view(), name='listing-detail'),
    path('board/<int:board_id>/listing/add/', ListingCreate.as_view(), name='listing-add'),
    path('board/<int:board_id>/listing/<int:listing_id>/update/', ListingUpdate.as_view(), name='listing-update'),
    path('board/<int:board_id>/listing/<int:listing_id>/delete/', ListingDelete.as_view(), name='listing-delete'),
    path('board/<int:board_id>/listing/<int:listing_id>/item/add', ItemCreate.as_view(), name='item-add'),
    path('board/<int:board_id>/listing/<int:listing_id>/item/<int:item_id>/detail', ItemDetail.as_view(), name='item-detail'),
    path('board/<int:board_id>/listing/<int:listing_id>/item/<int:item_id>/update', ItemUpdate.as_view(), name='item-update'),
    path('board/listing/item/<int:item_id>/milestone/add', MilestoneCreate.as_view(), name='milestone-add'),
    path('board/listing/item/<int:item_id>/milestone/<int:milestone_id>/update', MilestoneUpdate.as_view(), name='milestone-update'),
    path('board/listing/item/<int:item_id>/milestone/<int:milestone_id>/update', milestoneAjaxUpdate, name='milestone-ajax-update'),
    path('board/listing/item/<int:item_id>/comment/add', CommentCreate.as_view(), name='comment-add'),
]

divisions/urls.py
from django.urls import path, re_path
from divisions.views import (
    SectionList, SectionDetail, SectionCreate, SectionUpdate, SectionDelete,
    TeamList, TeamDetail, TeamCreate, TeamUpdate, TeamDelete
)

app_name = 'divisions'
urlpatterns = [
    path('sections/', SectionList.as_view(), name='section-list'),
    path('section-detail/<int:section_id>/', SectionDetail.as_view(), name='section-detail'),
    path('section/add/', SectionCreate.as_view(), name='section-add'),
    path('section/<int:section_id>/update', SectionUpdate.as_view(), name='section-update'),
    path('teams/', TeamList.as_view(), name='team-list'),
    path('team-detail/<int:team_id>/', TeamDetail.as_view(), name='team-detail'),
    path('team/add/', TeamCreate.as_view(), name='team-add'),
    path('team/<int:team_id>/update', TeamUpdate.as_view(), name='team-update'),
]

users/urls.py
from django.urls import path, re_path
from . import views
from .views import UserProfileCreate, UserProfileDetail, UserProfileUpdate

app_name = 'users'
urlpatterns = [
    path('new-user/', views.signup, name='create-user'),
    path('create-profile/', UserProfileCreate.as_view(), name='create-profile'),
    path('user/<int:user_id>/profile-detail/<int:profile_id>', UserProfileDetail.as_view(), name='profile-detail'),
    path('user/<int:user_id>/profile/<int:profile_id>/update', UserProfileUpdate.as_view(), name='update-profile'),
]

divisions/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from boards.models import Board
from django.urls import reverse

class Base(models.Model):
	"""
		A Base Model (Mixin Like) for the creation of Section and Team Models through Inheritance
	"""
	name = models.CharField(max_length = 50)
	description = models.TextField(blank = True)
	creator = models.ForeignKey('auth.User', on_delete = models.PROTECT)
	created = models.DateTimeField(default = timezone.now)

	class Meta:
		abstract = True

	def __str__(self):
		return self.name

class Team(Base):
	"""
		A Team can be thought of as a group:
	"""
	members = models.ManyToManyField('auth.User', related_name='team_members', blank =True)
	boards = models.ManyToManyField('boards.Board', related_name='team_boards', blank =True)
	
	def get_absolute_url(self):
		return reverse('divisions:team-detail', kwargs={'team_id': self.pk})

class Section(Base):
	"""
		Inherits from Base and create Various Sections for use
		Each Section or sub section can have their own own teams
	"""
	teams = models.ManyToManyField(Team, related_name='section_teams', blank = True)
	members = models.ManyToManyField('auth.User', related_name='section_members', blank =True)
	boards = models.ManyToManyField('boards.Board', related_name='section_boards', blank =True)
	
	def get_absolute_url(self):
		return reverse('divisions:section-detail', kwargs={'section_id': self.pk})

divisions/views/views_sections.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from divisions.models import Section
from boards.models import Board
from django.contrib.auth.mixins import LoginRequiredMixin


class SectionList(LoginRequiredMixin, ListView):
	model = Section

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['header'] = "Sections"
		context['sub_header'] = "Though Divided we work together towards a common goal #specialisation"
		context['colorStyle'] = "section-color"
		return context

class SectionDetail(LoginRequiredMixin, DetailView):
	model = Section
	pk_url_kwarg = 'section_id'
	context_object_name = 'object_detail'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['its_a'] = "Section"
		context['is_a_Team'] = False
		return context


class SectionCreate(LoginRequiredMixin, CreateView):
	model = Section
	fields = ['name', 'description', 'teams', 'members', 'boards']
	template_name = 'create-form.html'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['formTitle'] = "Add Section"
		return context

	def form_valid(self, form):
		form.instance.creator = self.request.user
		return super().form_valid(form)

class SectionUpdate(LoginRequiredMixin, UpdateView):
	model = Section
	pk_url_kwarg = 'section_id'
	fields = ['name', 'description', 'teams', 'members', 'boards']
	template_name = 'create-form.html'

class SectionDelete(LoginRequiredMixin, DeleteView):
	model = Section
	pk_url_kwarg = 'section_id'
	template_name = 'confirm-delete.html'
	success_url = "/"

divisions/views/views_teams.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from divisions.models import Team
from boards.models import Board
from django.contrib.auth.mixins import LoginRequiredMixin

class TeamList(LoginRequiredMixin, ListView):
	model = Team

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['header'] = "Teams"
		context['sub_header'] = "We are groups of individuals working towards a common goal"
		context['colorStyle'] = "team-color"
		return context

class TeamDetail(LoginRequiredMixin, DetailView):
	model = Team
	pk_url_kwarg = 'team_id'
	context_object_name = 'object_detail'
	
	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['its_a'] = "Team"
		context['is_a_Team'] = True
		return context

class TeamCreate(LoginRequiredMixin, CreateView):
	model = Team
	fields = ['name', 'description','members', 'boards']
	template_name = 'create-form.html'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['formTitle'] = "Create Team"
		return context

	def form_valid(self, form):
		form.instance.creator = self.request.user
		return super().form_valid(form)

class TeamUpdate(LoginRequiredMixin, UpdateView):
	model = Team
	pk_url_kwarg = 'team_id'
	fields = ['name', 'description','members', 'boards']
	template_name = 'create-form.html'

class TeamDelete(LoginRequiredMixin, DeleteView):
	model = Team
	pk_url_kwarg = 'team_id'
	template_name = 'confirm-delete.html'
	success_url = "/"

divisions/templates/divisions/section_detail.html
{% extends 'base.html' %}

{% block content %}
	<div class="container">
		<h2>{{ its_a }}: {{ object_detail.name }}</h2>
		<hr>
		<div class="card-body bg-white">
			<p class="card-text">
				{{ object_detail.description }}
			</p>
		</div>
		<hr>
			<nav style="margin-bottom: 2rem;">
				<div class="nav nav-tabs" id="nav-tab" role="tablist">
					<a class="nav-item nav-link disabled" id="nav-home-tab" data-toggle="tab" href="#nav-discusions" role="tab" aria-controls="nav-home" aria-selected="true">Discussions</a>
					<a class="nav-item nav-link active" id="nav-profile-tab" data-toggle="tab" href="#nav-boards" role="tab" aria-controls="nav-profile" aria-selected="false">Our Boards</a>
					{% if not is_a_Team %}
					<!-- A team has no teams -->
					<a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-teams" role="tab" aria-controls="nav-profile" aria-selected="false">Our Teams</a>
					{% endif %}
				</div>
			</nav>
			<div class="tab-content" id="nav-tabContent">
				<!-- Discusions -->				
				<div class="tab-pane fade show disbled" id="nav-discusions" role="tabpanel" aria-labelledby="nav-home-tab">
					<div class="card-columns">
						{% for object in object_detail.discusions.all %}
							{% include './includes/board.html' %}	
						{% empty %}
							There are no ongoing discusions in this {{ its_a }}
						{% endfor %}
					</div>
				</div>
				<!-- Boards -->					
				<div class="tab-pane fade show  active" id="nav-boards" role="tabpanel" aria-labelledby="nav-boards-tab">
					<div class="card-columns">	
						<!-- get boards belonging to this Section using .boards.all direct manager -->
						{% if not is_a_Team %}						
							{% for object in object_detail.boards.all %}
								{% url 'boards:board-detail' board_id=object.pk as the_url %}
								{% include './includes/board.html' with the_url=the_url colorStyle='board-color' %}	
							{% empty %}
									There are no Boards in this {{ its_a }}
							{% endfor %}
						<!-- get boards belonging to this Team using .board_sections.all reverse manager -->
						{% else %}
							{% for object in object_detail.boards.all %}
								{% url 'boards:board-detail' board_id=object.pk as the_url %}
								{% include './includes/board.html' with the_url=the_url colorStyle='board-color' %}	
							{% empty %}
									There are no Boards in this {{ its_a }}
							{% endfor %}
						{% endif %}
					</div>
				</div>		
				{% if not is_a_Team %}		
				<!-- Teams : only in boards-->				
					<div class="tab-pane fade show" id="nav-teams" role="tabpanel" aria-labelledby="nav-teams-tab">
						<div class="card-columns">
							<!-- Get teams belonging to this Section using .teams.all -->
							{% for object in object_detail.teams.all %}
								{% url 'divisions:team-detail' team_id=object.pk as the_url %}
								{% include './includes/board.html' with the_url=the_url colorStyle='team-color' %}	
							{% empty %}
								There are no Teams in this {{ its_a }}	
							{% endfor %}							
						</div>
					</div>	
				{% endif %}			
			</div>
	</div>
{% endblock %}

divisions/templates/divisions/section_list.html
{% extends 'base.html' %}

{% block content %}	
	<div class="row">
		<div class="col-8">				
			<h3>{{ header }}</h3>
		</div>
		<div class="col-3"> 
			{% block create_link %}
				<a class="float-right add-color" href="{% url 'divisions:section-add' %}">
					Add Section	
				</a>
			{% endblock %}
		</div>
	</div>
	<hr>
	<p class="lead text-muted bg-white">{{ sub_header }}</p>
	<hr>
	<div class="card-columns">
		{% for section_or_team in object_list %}	
			<!-- Board -->	
			<div class="card">
				<div class="card-body {{ colorStyle }}">
				    <h5 class="card-title"> 
						{% block section_or_team_link %}
							<a href="{% url 'divisions:section-detail' section_id=section_or_team.pk %}" class="card-link text-center text-black">{{ section_or_team.name }}</a>
						{% endblock %}
				    </h5>
				  <hr>
					  <div class="card-body bg-white">
					    <p class="card-text">
					    	{{ section_or_team.description }}
					    	<span class="cardTextMore">
					    		<a href="#">
					    			<i class="far fa-edit"></i>
					    		</a>
					    	</span>
					    </p>
					</div>
					<hr>		   
				</div>
			</div>
			<!-- / Board -->
		{% endfor %}
	</div>
	
{% endblock %}

divisions/templates/divisions/subsection_detail.html
{% extends 'base.html' %}

{% block content %}
	<div class="container">
		<h4>Section: {{ subsection_detail.mainSection.name }}</h4>
		<h6>Sub-Section: {{ subsection_detail.name }}</h6>
		<hr>
	</div>
{% endblock %}

divisions/templates/divisions/team_detail.html
{% extends 'divisions/section_detail.html' %}

divisions/templates/divisions/team_list.html
{% extends 'divisions/section_list.html' %}

  
{% block create_link %}
<a class="float-right add-color" href="{% url 'divisions:team-add' %}">
    Add Team	
</a>
{% endblock %}


{% block section_or_team_link %}
    <a href="{% url 'divisions:team-detail' team_id=section_or_team.pk %}" class="card-link text-center text-black {
        color: #000;
    }">{{ section_or_team.name }}</a>
{% endblock %}